
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: orders
    chart: orders-0.6.0
    heritage: Tiller
    release: bluecompute
    tier: backend
    version: v1
  name: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
      chart: orders-0.6.0
      heritage: Tiller
      release: bluecompute
      tier: backend
      version: v1
  template:
    metadata:
      labels:
        app: orders
        chart: orders-0.6.0
        heritage: Tiller
        release: bluecompute
        tier: backend
        version: v1
    spec:
      containers:
      - env:
        - name: SERVICE_PORT
          value: "8084"
        - name: JAVA_TMP_DIR
          value: /spring-tmp
        - name: MYSQL_HOST
          value: bluecompute-orders-mariadb
        - name: MYSQL_PORT
          value: "3307"
        - name: MYSQL_DATABASE
          value: ordersdb
        - name: MYSQL_USER
          value: dbuser
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mariadb-password
              name: orders-mariadb-secret
        - name: HS256_KEY
          valueFrom:
            secretKeyRef:
              key: key
              name: bluecompute-hs256key
        image: __IMAGE__
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /health
            port: 8094
            scheme: HTTP
          initialDelaySeconds: 35
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: orders
        ports:
        - containerPort: 8084
          protocol: TCP
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /health
            port: 8094
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 384Mi
          requests:
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 2000
        volumeMounts:
        - mountPath: /spring-tmp
          name: spring-tmp
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - /bin/bash
        - -c
        - until mysql -h ${MYSQL_HOST} -P ${MYSQL_PORT} -u${MYSQL_USER} -p${MYSQL_PASSWORD}
          -e status; do echo waiting for mariadb; sleep 1; done
        env:
        - name: MYSQL_HOST
          value: bluecompute-orders-mariadb
        - name: MYSQL_PORT
          value: "3307"
        - name: MYSQL_DATABASE
          value: ordersdb
        - name: MYSQL_USER
          value: dbuser
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mariadb-password
              name: orders-mariadb-secret
        image: mysql:5.7.14
        imagePullPolicy: IfNotPresent
        name: test-mariadb
        resources:
          limits:
            memory: 384Mi
          requests:
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 2000
      volumes:
      - emptyDir:
          medium: Memory
        name: spring-tmp
